sudo: required
services:
    - docker

script:
    - docker build -t surabhdesigns/node .
    - docker images surabhdesigns/node

before_deploy:
    - docker login -u surabhi0404 -p Surabhig9@

deploy:
    provider: script
    script: docker push mannaydesigns/node
    on:
        branch: master
